c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]

c_stdlib_version:
  - 2.17  # [linux]
  - 11.0  # [osx]

python:
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython

packages:
  - numpy
