c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]

c_stdlib_version:
  - 2.17  # [linux]
  - 11.0  # [osx]
  
root:
  - 6.32
#  - 6.34 # yoda <1.9 not compatible with ROOT6.34 due to python >=3.11 conflict.

packages:
  - root
